name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Tag Docker image
      run: |
        docker tag vscode_ext ${{ secrets.DOCKER_USERNAME }}/vscode_ext

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/vscode_ext

dependency-submission:

runs-on: ubuntu-latest
permissions:
  contents: write
